#!/bin/bash

./initialise_database
echo -e "\nStarting tests"

. venv/bin/activate

# Silently start the Flask server in the background
./start_server > /dev/null 2>&1 &
pytest "${@}"

# Shut down the Flask server
# (killing the most recent background job via 'kill %1' doesn't work here)
# Find the process ID of the running 'start_server' script
# (killing this process doesn't kill the underlying server process, so we need
#  to find the PID of the python3 instance that was launched by the script)
START_SERVER_PID=$(ps --no-header -C start_server | awk '{print $1}')
PYTHON_PID=$(ps --no-header --ppid $START_SERVER_PID | awk '{print $1}')
# Killing the python process also stops all of the child gunicorn instances
kill $PYTHON_PID
