"""
Runs sqlalchemy.create_all() to generate all database tables before the server
is first started. If the tables were to be generated by the server as it starts
up, they'll be generated correctly but will cause the server program to crash.
"""

import os
import sys

# Append parent directory to python path. Allows the Flask app to be imported
# while this script is inside the scripts/ directory.
sys.path.append(os.getcwd())

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import Config

app = Flask(__name__)
app.config.from_object(Config)
db = SQLAlchemy(app)

from app import models

db.create_all()
